version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # or any image suitable for your environment
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt  # Assuming you have a requirements.txt

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest tests/  # Assuming you're using pytest and your tests are in the 'tests/' directory

      - store_artifacts:
          path: test-results/
          destination: test-results

      - store_test_results:
          path: test-results/